#!/bin/bash

## AINA
## a .bash_profile for OSX love

initial_pwd="$PWD"
aina_root="${initial_pwd}/aina"
sm_path="$PWD"

#
# Include user configs
#
. "${aina_root}/config/user"

#
# Include core files
#
declare -a CORE_FILES=( variables functions new load )

for core_file in ${CORE_FILES[@]}; do
	. "${aina_root}/core/${core_file}"
done

# Libs
. "${aina_root}/lib/wordpress/init"

###########
## ALIAS ##
###########
# Browsers
alias safari="open -a safari"
alias chrome="open -a google\ chrome"
alias ff="open -a firefox"
alias opera="open -a opera"

# Editors
alias esp="open -a espresso"
alias sublime="open -a sublime\ text\ 2"

# Utils
alias less="open -a less"
alias sequel="open -a sequel\ pro"

# Adobe fellas
alias ai="open -a adobe\ illustrator"

##########
## AINA ##
##########
aina(){
	if [ ! $1 ]; then
	    echo "Welcome to Aina! Please, type a command";
	fi
	if fn_exists $1; then
        $i "$@"
        return
	fi
	echo "Hey, $1 does not exist! Duh."
}