#!/bin/bash

## AINA
## a .bash_profile for OSX love

initial_pwd="$PWD"
aina_root="${initial_pwd}/aina"
sm_path="$PWD"

. "${aina_root}/config/user"
. "${aina_root}/core/variables"
. "${aina_root}/core/new"

###########
## ALIAS ##
###########
# Browsers
alias safari="open -a safari"
alias chrome="open -a google\ chrome"
alias ff="open -a firefox"
alias opera="open -a opera"

# Editors
alias esp="open -a espresso"
alias sublime="open -a sublime\ text\ 2"

# Utils
alias server="open -a mamp"
alias less="open -a less"
alias sequel="open -a sequel\ pro"

# Adobe fellas
alias ai="open -a adobe\ illustrator"


###############
## FUNCTIONS ##
###############

# Go
# Opens $1 uri in $2 browser. If no browser is passed, uses Safari by default 
go(){
	if [ ! $2 ]; then
	    safari http://$1
	    return
	fi
	case $2 in
	    chrome)
	        chrome http://$1 ;;    
	    ff)
	        ff http://$1;;
	    safari)
	        safari http://$1;;
	    opera)
	        opera http://$1;;
	esac
}

##########
## AINA ##
##########


aina(){
	if [ ! $1 ]; then
	    echo "Welcome to Aina! Please, type a command";
	fi
	case $1 in
	    new)
	        new
	        ;;
		load)
			# Load 
			# Loads work environment
			server;
			cd ~/$server/$2;
			open -a espresso $2.esproj;
			chrome http://localhost:8888;;
		update)
			# Update
			case $2 in
				wordpress)
					cd ~/$server/aina/$new_dir/tmp;
					curl http://wordpress.org/latest.tar.gz > ~/$server/aina/$new_dir/tmp/$wp.tar.gz;
					gunzip -c $wp.tar.gz | tar xopf -; #gunzip -c wp.tar.gz > wp; #I'd like ton rename the file after decompress
					cp -R -v ~/$server/aina/$new_dir/tmp/$wp ~/$server/aina/$new_dir/$wp;
					rm -R $wp $wp.tar.gz;
					echo "WordPress has been updated";;
			esac
	esac
}