#!/bin/bash

###############
## FUNCTIONS ##
###############

# Go
# Opens uri $1 in browser $2. If no browser is passed, uses $default_browser 
go(){
	if [ ! $2 ]; then
	    open -a $default_browser http://$1
	    return
	else
		if [ $2 == 'chrome' ]; then
	        open -a google\ chrome http://$1
	    else
	    	open -a $2 http://$1
		fi
	fi
}

# Function Exists
# http://stackoverflow.com/a/9002012
fn_exists() {
  # appended double quote is an ugly trick to make sure we do get a string -- if $1 is not a known command, type does not output anything
  [ `type -t $1`"" == 'function' ]
}

file_exists() {
  # appended double quote is an ugly trick to make sure we do get a string -- if $1 is not a known command, type does not output anything
  [ `type -t $1`"" == 'file' ]
}

start_server(){
	open -a mamp
}

#
# Returns string with first letter capitalized
#
ucfirst(){
	local GO=$1
	local RETURN="$(tr '[:lower:]' '[:upper:]' <<< ${GO:0:1})${GO:1}"
	echo $RETURN 
}