#!/bin/bash

###############
## FUNCTIONS ##
###############

# Opens browser
open_browser(){
	case $1 in
		chrome)
			open -a google\ chrome
			return
			;;
	esac
	open -a $1
	return
}

# Go
# Opens uri $1 in browser $2. If no browser is passed, uses $default_browser 
go(){
	if [ ! $2 ]; then
	    open_browser $default_browser http://$1
	    return
	fi
	case $2 in
	    chrome|firefox|safari|opera)
	        open_browser $2 http://$1
	        ;;    
	esac
}

# Function Exists
# http://stackoverflow.com/a/9002012
fn_exists() {
  # appended double quote is an ugly trick to make sure we do get a string -- if $1 is not a known command, type does not output anything
  [ `type -t $1`"" == 'function' ]
}

file_exists() {
  # appended double quote is an ugly trick to make sure we do get a string -- if $1 is not a known command, type does not output anything
  [ `type -t $1`"" == 'file' ]
}

start_server(){
	open -a mamp
}