#!/bin/bash

# New
# Creates a new project from $1 code repo in new $2 folder
# Files in the new dir will not be overwritten, in case it already exists

new(){
	if [ ! $1 ]; then
		echo "No code repo was specified"	
		return
	fi
	if [ ! $2 ]; then
		echo "The new project name was not specified"	
		return
	fi
	if [ ! -d "$aina_root/$new_dir" ]; then
        echo "You haven't created the code repository yet."
        return
	fi
	if [ ! -d "$aina_root/$new_dir/$1" ]; then
        echo "There's no code repository named $1. Please, check your repos names ;-)"
        return
	fi
	cp -R -n $aina_root/$new_dir/$1 ~/$server_dir/$2
}