#!/bin/bash

# User configs

# Replace with your own

server_dir="localhost" # Your local server folder name (i.o.w. where you store your working projects)
default_browser="firefox" # Your prefered browser