#!/bin/bash

# --------------------
# Variables declaration
# --------------------

# If you left current directory blank, it will take the current directory 
DIRECTORY="/Applications/MAMP/htdocs/"

# wordpress url must be a zip to download
WORDPRESS_URL="http://wordpress.org/latest.zip"

# Theme must be a git repository
THEME_URL="https://github.com/Automattic/_s.git"

# Local database with MAMP
DB_USER='root'
DB_PASSWORD='root'
DB_HOST='localhost'

# Local URL
LOCAL_URL='http://localhost:8888/'

# git
WP_GITIGNORE=".htaccess
wp-config.php
wp-content/uploads/
wp-content/blogs.dir/
wp-content/upgrade/
wp-content/backup-db/
wp-content/advanced-cache.php
wp-content/wp-cache-config.php
sitemap.xml
*.log
wp-content/cache/
wp-content/backups/
sitemap.xml.gz"