#!/bin/bash

#
# User configs
#

# Starter Theme. Must be a github repository
STARTER_THEME_URL="https://github.com/Automattic/_s.git"

# Local database settings
DB_USER='root'
DB_PASSWORD='root'
DB_HOST='localhost'