#!/bin/bash

#
# Credits: 
# This function is almost a copy&paste of Jeremy Castelli's WP New Project script
# https://github.com/jeremycastelli/Wordpress-new-project-config
#

install()
{
	if [[ $WP != true ]]; then
		echo "$FUNCNAME is not an Aina command. Try [lib] $FUNCNAME instead"
		return
	fi

	# echo "This script will:"
	# echo "1. Make a new install of WordPress with the project name"
	# echo "2. Create a database for the project and set the wp-config.php"
	# echo "3. Init a Git repository"
	# echo
	# echo "Do you wish to proceed? (Y/N)"

	echo "Project Name:"
	read PROJECT_NAME
	while [[ -z "$PROJECT_NAME" ]]; do
		echo "Please, type your project name:"
		read PROJECT_NAME
	done

	#
	# Set PROJECT_PATH & THEME_PATH for reuse
	#
	local PROJECT_PATH=~/$server_dir/$PROJECT_NAME
	local THEME_PATH=$PROJECT_PATH/$WP_THEMES_PATH/$PROJECT_NAME

	echo "Database Name:"
	read DB_NAME
	while [[ -z "$DB_NAME" ]]; do
		echo "Please, type a name for this project database:"
		read DB_NAME
	done

	echo "Database prefix (hit Y if you want the default wp_):"
	read DB_PREFIX
	while [[ -z "$DB_PREFIX" ]]; do
		echo "Please, type a prefix for the database tables, or hit Y if you want the default wp_:"
		read DB_PREFIX
	done
	# Set DB_PREFIX to default if that's the case
	if [[ $DB_PREFIX =~ ^[Yy]$ ]]; then
		DB_PREFIX='wp_'
	fi

	echo "Do you want Debug set to true? (Y/N)"
	read WP_DEBUG
	while [[ -z "$WP_DEBUG" ]]; do
		echo "Do you want Debug set to true? (Y/N)"
		read DB_PREFIX
	done
	if [[ $WP_DEBUG =~ ^[Yy]$ ]]; then
		WP_DEBUG="true"
	else
		WP_DEBUG="false"
	fi
	
	# 
	# Install WordPress
	# 
	echo "Installating WordPress..."
	new wordpress $PROJECT_NAME

	# 
	# Fetch base theme
	# 
	echo 'Remove default themes and plugins...'
	git clone $STARTER_THEME_URL $THEME_PATH

	# 
	# Remove default themes
	#
	echo 'Remove default themes and plugins...'
	for name in ${DESTROY_THEMES[@]}; do
		rm -r $PROJECT_PATH/$WP_THEMES_PATH/$name
	done

	#
	# Remove Hello Dolly plugin
	#
	rm $PROJECT_PATH/$WP_PLUGINS_PATH/hello.php
	
	#
	# Create Database
	#
	echo "Creating database $DB_NAME"
	/Applications/MAMP/Library/bin/mysql --host=$DB_HOST -u$DB_USER -p$DB_PASSWORD -e "create database "$DB_NAME

	#
	# Create wp-config
	#
	echo "Creating wp-config..."
	touch ~/$server_dir/$PROJECT_NAME/wp-config.php
	echo "<?php
/**
 * The base configurations of the WordPress.
 *
 * This file has the following configurations: MySQL settings, Table Prefix,
 * Secret Keys, WordPress Language, and ABSPATH. You can find more information
 * by visiting {@link http://codex.wordpress.org/Editing_wp-config.php Editing
 * wp-config.php} Codex page. You can get the MySQL settings from your web host.
 *
 * This file is used by the wp-config.php creation script during the
 * installation. You don't have to use the web site, you can just copy this file
 * to 'wp-config.php' and fill in the values.
 *
 * @package WordPress
 */

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', '"$DB_NAME"');

/** MySQL database username */
define('DB_USER', '"$DB_USER"');

/** MySQL database password */
define('DB_PASSWORD', '"$DB_PASSWORD"');

/** MySQL hostname */
define('DB_HOST', '"$DB_HOST"');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
define('AUTH_KEY',         'put your unique phrase here');
define('SECURE_AUTH_KEY',  'put your unique phrase here');
define('LOGGED_IN_KEY',    'put your unique phrase here');
define('NONCE_KEY',        'put your unique phrase here');
define('AUTH_SALT',        'put your unique phrase here');
define('SECURE_AUTH_SALT', 'put your unique phrase here');
define('LOGGED_IN_SALT',   'put your unique phrase here');
define('NONCE_SALT',       'put your unique phrase here');

/**#@-*/

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each a unique
 * prefix. Only numbers, letters, and underscores please!
 */
\$table_prefix  = '"$DB_PREFIX"';

/**
 * WordPress Localized Language, defaults to English.
 *
 * Change this to localize WordPress. A corresponding MO file for the chosen
 * language must be installed to wp-content/languages. For example, install
 * de_DE.mo to wp-content/languages and set WPLANG to 'de_DE' to enable German
 * language support.
 */
define('WPLANG', '');

/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 */
define('WP_DEBUG', "$WP_DEBUG");

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');" > ~/$server_dir/$PROJECT_NAME/wp-config.php

	#
	# Done
	#
	echo "Hooray! You successfully installed WordPress."
}